# Generated by Django 4.1.4 on 2023-01-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Abuja', 'Nigeria'), ('Accra', 'Ghana'), ('Addis Abba', 'Ethiopia'), ('Algiers', 'Algeria'), ('Antananarivo', 'Madagascar'), ('Asmera', 'Eritrea'), ('Bamako', 'Mali'), ('Bangu', ' Central African Republic'), ('Banjul', 'Gambia'), ('Bissau', 'Guinea-Bissau'), ('Brazzaville', ' Republic of the Congo'), ('Bujumbura', ' Burundi'), ('Cairo', 'Egypt'), ('Conakry', ' Guinea'), ('Dakar', ' Senegal'), ('Dar es Salaam', ' Tanzania'), ('Djibouti City', ' Djibouti'), ('Freetown', 'Sierra Leone'), ('Gaborone', 'Botswana'), ('Harare', 'Zimbabwe'), ('Juba', ' South Sudan'), ('Kampala', ' Uganda'), ('Khartoum', ' Sudan'), ('Kigali', 'Rwanda'), ('Kinshasa', ' Democratic Republic of the Congo'), ('Libreville', ' Gabon'), ('Lilongwe', ' Malawi'), ('Lome', ' Togo'), ('Luanda', ' Angola'), ('Lusaka', ' Zambia'), ('Malabo', ' Equatorial Guinea'), ('Maputo', ' Mozambique'), ('Maseru', 'Lesotho'), ('Mbabane', ' Swaziland'), ('Mogadishu', ' Somalia'), ('Monrovia', ' Liberia'), ('Moroni', 'Comoros'), ('Nairobi', ' Kenya'), ('N’Djamena', ' Chad'), ('Niamey', ' Niger'), ('Nouakchott', ' Mauritania'), ('Ouagadougou', ' Burkina Faso'), ('Port Louis', ' Mauritius'), ('Pretoria', ' South Africa'), ('Porto Novo', ' Benin'), ('Praia', ' Cape Verde'), ('Rabat', ' Morocco'), ('Tripoli', ' Libya'), ('Tunis', ' Tunisia'), ('Victoria', ' Seychelles'), ('Windhoek', ' Namibia'), ('Yamoussoukro', ' Cote d’Ivoire'), ('Yaoundé', ' Cameroon')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
